# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 02:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapers', '0002_auto_20160801_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessageperson',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='textmessageperson_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
