# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_auto_20160808_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='time_sent',
            field=models.DateTimeField(max_length=25),
        ),
    ]
