# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_auto_20160814_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='partner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='time_sent',
            field=models.DateTimeField(),
        ),
    ]
