# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0006_auto_20160814_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessageperson',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textmessageperson_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
