# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0011_auto_20160905_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('first_name', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('last_name', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('username', models.CharField(default=b'PLACEHOLDER', max_length=1000)),
                ('avatar', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instagramhashtag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.InstagramPerson'),
        ),
    ]
