# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0012_auto_20161001_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
                ('happiness', models.FloatField(default=0)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapers.InstagramPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='instagramhashtag',
            name='author',
        ),
        migrations.AddField(
            model_name='instagramhashtag',
            name='original_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrapers.InstagramPost'),
            preserve_default=False,
        ),
    ]
