# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0019_auto_20160412_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterpost',
            old_name='hhex_key',
            new_name='hex_key',
        ),
    ]
