# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0021_remove_twitterpost_hex_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterpostmarkovpart',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='twitterpostmarkov',
            name='content',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterpostmarkov',
            name='original_tweet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TwitterPostMarkovPart',
        ),
    ]
