# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0022_auto_20160417_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpost',
            name='happiness',
            field=models.FloatField(default=0),
        ),
    ]
