# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0027_auto_20160509_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='real_name',
            new_name='name',
        ),
    ]
