# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('default', '0003_alter_email_max_length'),
        ('scrapers', '0028_auto_20160510_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='twitterperson',
            options={},
        ),
        migrations.RemoveField(
            model_name='markovchain',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='author',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='person_ptr',
        ),
        migrations.AddField(
            model_name='twitterperson',
            name='avatar',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterperson',
            name='name',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterperson',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapers.TwitterPerson'),
        ),
        migrations.AddField(
            model_name='twitterpostmarkov',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapers.TwitterPerson'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
