# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0030_remove_twitterperson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterperson',
            name='name',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
    ]
