# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0031_twitterperson_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterperson',
            old_name='name',
            new_name='real_name',
        ),
    ]
