# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0034_auto_20160528_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
                ('word2', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
                ('final_word', models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True)),
                ('beginning', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='twitterpost',
            name='happiness',
        ),
        migrations.RemoveField(
            model_name='twitterpostcache',
            name='beginning',
        ),
        migrations.RemoveField(
            model_name='twitterpostcache',
            name='final_word',
        ),
        migrations.RemoveField(
            model_name='twitterpostcache',
            name='id',
        ),
        migrations.RemoveField(
            model_name='twitterpostcache',
            name='word1',
        ),
        migrations.RemoveField(
            model_name='twitterpostcache',
            name='word2',
        ),
        migrations.AddField(
            model_name='sentence',
            name='happiness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='twitterpostcache',
            name='sentencecache_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapers.SentenceCache'),
            preserve_default=False,
        ),
    ]
