# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0035_auto_20160529_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterpost',
            name='sentence_ptr',
        ),
        migrations.RemoveField(
            model_name='twitterpostcache',
            name='sentencecache_ptr',
        ),
        migrations.RemoveField(
            model_name='twitterpostmarkov',
            name='markovchain_ptr',
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='content',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='happiness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterpostcache',
            name='beginning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitterpostcache',
            name='final_word',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterpostcache',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterpostcache',
            name='word1',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterpostcache',
            name='word2',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterpostmarkov',
            name='content',
            field=models.CharField(default=b'PLACEHOLDER', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitterpostmarkov',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterpostmarkov',
            name='randomness',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='MarkovChain',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='SentenceCache',
        ),
    ]
