# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0037_literatureperson_sentence_sentencecache_sentencemarkov'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentence',
            new_name='LiteratureSentence',
        ),
        migrations.RenameModel(
            old_name='SentenceMarkov',
            new_name='LiteratureSentenceMarkov',
        ),
    ]
