# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_instagramcache'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramCache',
            new_name='InstagramPostCache',
        ),
    ]
