# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20161119_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='integrations.TwitterPerson')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.TwitterPerson')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterConversationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.TwitterConversation')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.TwitterPost')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.TwitterPerson')),
            ],
        ),
    ]
