# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-27 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20170319_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterconversationpost',
            old_name='post_author',
            new_name='author',
        ),
    ]
