# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_twitterconversation_twitterconversationpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterconversationpost',
            old_name='post',
            new_name='content',
        ),
    ]
